[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Proxy API requests to the Serverless Express function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Fallback for React Single Page Application (SPA) Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
